### ISSUE TITLE
where is fnl_model.pt?

### ISSUE THREAD

**Issue by heidapao2b** [georgeretsi/mushroom-pose#1]
Thank you for your working! I want to know where is fnl_model.pt .

**Comment by georgeretsi** [comment]
Hi there! Thanks for your interest in our work. The "fnl_model.pt" is not the correct name, since I have renamed this in "trained_model.pt" which exists in the repo. I've updated the code. This is to start training from an already well-performing model, but you can also try removing the load_state_dict commands (this may take several epochs).

**Comment by heidapao2b** [comment]
OK! Thank you very much！
